[package]
name = "pyr"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
pyr-arch.workspace = true
pyr-platform-qemu = { workspace = true, optional = true }

[features]
default = ["platform-qemu-virt"]
boot-tiny = ["platform-qemu-virt"]
boot-linux = ["platform-qemu-virt"]
platform-qemu-virt = ["dep:pyr-platform-qemu"]

[lints]
workspace = true
