[package]
name = "ember"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
pyr-arch.workspace = true
pyr-platform-qemu = { workspace = true, optional = true }
pyr = { path = "../pyr", default-features = false }

[features]
default = ["boot-tiny"]
boot-tiny = [
  "platform-qemu-virt",
  "pyr/boot-tiny",
  "pyr/platform-qemu-virt"
]
boot-linux = [
  "platform-qemu-virt",
  "pyr/boot-linux",
  "pyr/platform-qemu-virt",
]
platform-qemu-virt = ["dep:pyr-platform-qemu"]

[lints]
workspace = true
